CREATE TABLE `T_ACCOUNT` (
  `ID`  INTEGER(20) NOT NULL COMMENT 'userid',
  `TOTAL_BALANCE`  DECIMAL(16,2) NOT NULL COMMENT 'price',
  `RESERVED`  TINYINT(1) NOT NULL COMMENT 'reserved',
  PRIMARY KEY (`ID`)
)
  ENGINE=InnoDB
  DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
;